<a href="https://colab.research.google.com/github/heyroha/Python/blob/main/infrlearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
s = {10, 20, 30 , 40, 50, 10, 10, 10}

for i in s:
    print(i)

#set은 순서가 정해져있지 않다.
#리스트나 문자열도 set으로 변환 가능.
#중복이 허용되지 않음.
#set안에는 set 넣을 수 없다.

50
20
40
10
30


In [ ]:
for i in range(10):
    print(i)
    if i == 5:
        break

else:
    print('good job!')
    #else는 정상 중단일때만 출력된다. 여기서 break 은 정상이 아니므로 출력.



0
1
2
3
4
5


In [ ]:
l  = list(range(101))
print(l)

ll = [i for i in range(10)]
print(ll)

#for i in range(2,10):
#    for j in range(1,10):
#       print('{}*{}={}'.format(i,j,i*j))

lll = ['{}*{}={}'.format(i,j,i*j) for i in range(2,10) for j in range(1,10)]
print(lll)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
['2*1=2', '2*2=4', '2*3=6', '2*4=8', '2*5=10', '2*6=12', '2*7=14', '2*8=16', '2*9=18', '3*1=3', '3*2=6', '3*3=9', '3*4=12', '3*5=15', '3*6=18', '3*7=21', '3*8=24', '3*9=27', '4*1=4', '4*2=8', '4*3=12', '4*4=16', '4*5=20', '4*6=24', '4*7=28', '4*8=32', '4*9=36', '5*1=5', '5*2=10', '5*3=15', '5*4=20', '5*5=25', '5*6=30', '5*7=35', '5*8=40', '5*9=45', '6*1=6', '6*2=12', '6*3=18', '6*4=24', '6*5=30', '6*6=36', '6*7=42', '6*8=48', '6*9=54', '7*1=7', '7*2=14', '7*3=21', '7*4=28', '7*5=35', '7*6=42', '7*7=49', '7*8=56', '7*9=63', '8*1=8', '8*2=16', '8*3=24', '8*4=32', '8*5=

In [ ]:
l = [(1,10),(2,20),(3,30),(4,40)]
for i in l: 리스트의 언팩킹1
    print(*i)

for i, j in l:
    print(i,j) #리스트의 언팩킹2

1 10
2 20
3 30
4 40
1 10
2 20
3 30
4 40


In [ ]:
for i, j in enumerate(range(100,1000,100),1): #print와 같은 빌트인 펑션.
    print(i,j) #데이터를 가져와서 순위를 매길때 사용


1 100
2 200
3 300
4 400
5 500
6 600
7 700
8 800
9 900


#**Class**

1. class name 첫 문자가 대문자
2. class 는 대부분 직접만지지 않음.
3. class 가 붕어빵 찍는 틀이라면 instance는 붕어빵.
4. object는 상속의 의미


In [ ]:
class Car():
    maxSpeed = 300
    maxPeople = 5
    def start(self):
        print('출발')
    def stop(self):
        print('정지')

class Hybrid(Car):
    battery = 1000
    batteryKm = 3000

k3 = Car()
k5 = Car()
k9 = Hybrid()
print(k3)
print(k9.maxPeople) #여기서 k9 은 hybrid class로 받았지만 object의 상속때문에 car class의 속성도 가지고 있는 것임.
print(k3.maxSpeed)

5
300


#**1.Numpy**


In [ ]:
import numpy as np

data = [[1,2,3],[4,5,6],[7,8,9]]

print(data)
print(type(data))

a = np.array(data) #np.array([구성하고 싶은 숫자데이터]) 의 형태로 구현
print(a) #대괄호를 두번 쓰면 2차원 배열을 만드는 것임

a.dtype

a = a.astype(np.float32) #형변환을 해줌
a

a[0][1] = np.nan #결측치 채워넣기

a


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
<class 'list'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([[ 1., nan,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.]], dtype=float32)

In [ ]:
np.arange(1,10,2) #range와 동일


array([1, 3, 5, 7, 9])

In [ ]:
np.arange(1,10).reshape(3,3) #구조를 바꿔줌

np.arange(1,13).reshape(3,2,2) #3칸으로 쪼개고 2줄로 나누고 2개의 원소가 들어간다



array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

#

In [ ]:
#**연산**

In [ ]:
data = np.arange(1,10).reshape(3,3)
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(data + data)
print(data - data)
print(data * data) #여기서 * 와 /는 행렬의 연산이 아닌 각 원소의 연산이다.
print(data / data)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print(np.dot(data,data)) #행렬의 *연산
print(data@data)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


##**차원**

In [ ]:
#스칼라
a = np.array(1) #array에 1을 넣은게 a 이다 즉 a[0]은 1
print(a)


print(a.shape) #형태
print(a.ndim) #몇차원인지

1
()
0


In [ ]:
#1차원 벡터

a = np.array([1,2,3,4,5]) #대괄호를 묶어주면 차원이 생기게 됨.
print(a)


print(a.shape) #형태 즉,5개의 형태를 가지고있다.
print(a.ndim) #몇차원인지

[1 2 3 4 5]
(5,)
1


In [ ]:
#2차원 행렬 = matrix

a = np.array([[1,2,3],[4,5,6]]) #대괄호의 개수가 차원의 개수
print(a)


print(a.shape) #형태 (x,y) x행과 y열을 가지고 있다는 것.
print(a.ndim) #몇차원인지

b = np.array([[1]])
print(b)
print(a.shape)
print(a.ndim) #대괄호가 2개니까 2차원 행렬이다.

[[1 2 3]
 [4 5 6]]
(2, 3)
2
[[1]]
(2, 3)
2


In [ ]:
#3차원 행렬 = Tensor

a = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]])
print(a)
print(a.shape)
print(a.ndim)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
(2, 3, 2)
3


##**Matrix의 유형**

In [ ]:
a = np.arange(12).reshape(2,3,2)
print(a)

b = np.ones(12) #ones를 사용해서도 행렬 만들 수 있음 /1로만 채워짐
print(b)
b = np.ones(12).reshape(2,3,2)
print(b)

c = np.zeros(12).reshape(2,3,2) #zeros를 사용해서도 행렬 만들 수 있음 /1로만 채워짐
print(c)

e = np.zeros([3,4])
print(e)

f = np.zeros([3,4,2])
print(f)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
#단위행렬

d = np.eye(3) #자신과 자신을 곱했을때 자신이 나오므로 eye를 사용한다고 생각하기
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
f = np.empty([2,3]) #empty는 0에 가까운 있는 값으로 채워줌

In [ ]:
g = np.full((3,4),1000) #만들어놓은 행렬에 1000으로 채워라
print(g)

h = np.linspace(2,10,6) #2부터 10까지 6개를 만들고 그 사이를 동등한 간격으로 만들어라. 여기서는 1.6으로 차이가 남
print(h)

[[1000 1000 1000 1000]
 [1000 1000 1000 1000]
 [1000 1000 1000 1000]]
[ 2.   3.6  5.2  6.8  8.4 10. ]


##**집계함수**

In [ ]:
a = np.arange(10).reshape(2,5)
print(a)

a[0][0] = 100
print(a)

a[0,1] = 1000
print(a)


[[0 1 2 3 4]
 [5 6 7 8 9]]
[[100   1   2   3   4]
 [  5   6   7   8   9]]
[[ 100 1000    2    3    4]
 [   5    6    7    8    9]]


In [ ]:
#평균
np.mean(a)

114.4

In [ ]:
#중앙값
np.median(a)

6.5

In [ ]:
#표준편차
np.std(a)

296.5485457728633

In [ ]:
#분산
np.var(a)

87941.04

In [ ]:
print(np.sum(a)) #합 - 원소를 모두 더한것

print(sum(a)) #각 행을 위아래로 더한것

print(np.sum(a,axis = 0)) #axis로 축을 설정해줘서 더한것 0은 위아래로 컬럼으로 1은 row로 더해줌
print(np.sum(a,axis = 1))



1144
[ 105 1006    9   11   13]
[ 105 1006    9   11   13]
[1109   35]


In [ ]:
#최대값
print(np.max(a))
#최소값
print(np.min(a))

print(np.max(a,axis = 1)) #각 행의 최대값
print(np.min(a,axis = 0)) #각 열의 최소값



1000
2
[1000    9]
[5 6 2 3 4]


#**2.Pandas**

In [ ]:
import pandas as pd

data = np.arange(0,50,10)
print(data)

[ 0 10 20 30 40]


In [ ]:
#인덱싱
a = pd.Series(data, index=['a','b','c','d','e'])
print(a)

b = pd.Series(data) #자동으로 인덱스 생성 0부터 명시적으로 생성해줌
print(b)

a     0
b    10
c    20
d    30
e    40
dtype: int64
0     0
1    10
2    20
3    30
4    40
dtype: int64


In [ ]:
print(a['b']) #a에서 b를 찾아서 반환
print(a.loc['b']) #location을 찾음
print(a.iloc[1]) #인덱스를 암시적으로 찾아서 1에 해당하는 애를 찾아다

10
10
10


##**산술연산**

In [ ]:
print(a)
print(a+10)
print(a*10)
print(a-10)
print(a**2)
print(a/5)
print(a%3)

a     0
b    10
c    20
d    30
e    40
dtype: int64
a    10
b    20
c    30
d    40
e    50
dtype: int64
a      0
b    100
c    200
d    300
e    400
dtype: int64
a   -10
b     0
c    10
d    20
e    30
dtype: int64
a       0
b     100
c     400
d     900
e    1600
dtype: int64
a    0.0
b    2.0
c    4.0
d    6.0
e    8.0
dtype: float64
a    0
b    1
c    2
d    0
e    1
dtype: int64


In [ ]:
print(a>15) #참 거짓으로 알려줌
print(a[a>15]) # 그 중에서 어떤 값이 15이상인지를 반환해줌.


a    False
b    False
c     True
d     True
e     True
dtype: bool
c    20
d    30
e    40
dtype: int64


In [ ]:
print(a.add(100))
print(a.sub(100))
print(a.mul(100))
print(a.div(100))
print(a.mod(100))
print(a.max())
print(a.min())
print(a.sum())
print(a.mean())
print(a.median())
print(a.std())
print(a.var())

a    100
b    110
c    120
d    130
e    140
dtype: int64
a   -100
b    -90
c    -80
d    -70
e    -60
dtype: int64
a       0
b    1000
c    2000
d    3000
e    4000
dtype: int64
a    0.0
b    0.1
c    0.2
d    0.3
e    0.4
dtype: float64
a     0
b    10
c    20
d    30
e    40
dtype: int64
40
0
100
20.0
20.0
15.811388300841896
250.0


##**Data Frame**

In [ ]:
rawData = np.random.randint(50,100,size = (4,3))
rawData

array([[95, 65, 74],
       [86, 92, 50],
       [53, 82, 86],
       [73, 78, 54]])

In [ ]:
df = pd.DataFrame(rawData,
                  index = ['1반','2반','1반','2반'],
                  columns = ['국','영','수'])

df

국   영   수
1반  95  65  74
2반  86  92  50
1반  53  82  86
2반  73  78  54

In [ ]:
#df[0] ->error
df['국'] #행렬, 배열과 다르게 여기는 column값이 먼저 들어간다.

1반    95
2반    86
1반    53
2반    73
Name: 국, dtype: int64

In [ ]:
df['평균'] = round((df['국']+df['영']+df['수'])/3, 2) #평균을 추가시킴
print(df)



국   영   수     평균
1반  95  65  74  78.00
2반  86  92  50  76.00
1반  53  82  86  73.67
2반  73  78  54  68.33

In [ ]:
df['nan'] = np.nan #결측치
df

국   영   수     평균  nan
1반  95  65  74  78.00  NaN
2반  86  92  50  76.00  NaN
1반  53  82  86  73.67  NaN
2반  73  78  54  68.33  NaN

In [ ]:
#column을 통으로 지우고 싶을때
del df['nan']
df

국   영   수     평균
1반  95  65  74  78.00
2반  86  92  50  76.00
1반  53  82  86  73.67
2반  73  78  54  68.33

In [ ]:
df[df.평균>75]

국   영   수    평균
1반  95  65  74  78.0
2반  86  92  50  76.0

In [ ]:
#df = df.drop(['평균'],axis = 'columns')
df


국   영   수
1반  95  65  74
2반  86  92  50
1반  53  82  86
2반  73  78  54

In [ ]:
#결측값 처리- 데이터가 비어있을때 처리

df = df.astype('float64')
df


국     영     수
1반  95.0  65.0  74.0
2반  86.0  92.0  50.0
1반  53.0  82.0  86.0
2반  73.0  78.0  54.0

In [ ]:
df['수'][2] = np.nan
df

국     영     수
1반  95.0  65.0  74.0
2반  86.0  92.0  50.0
1반  53.0  82.0   NaN
2반  73.0  78.0  54.0

In [94]:
print(df.dropna(axis = 0)) #행으로 결측값을 없애버리는데 이는 원본값을 지우는 건 아님.
#원본값을 지우려면 inplace = True
#df.dropna(axis = 0, inplace = True)

df.dropna(axis = 1)

       국     영     수
1반  95.0  65.0  74.0
2반  86.0  92.0  50.0
2반  73.0  78.0  54.0


국     영
1반  95.0  65.0
2반  86.0  92.0
1반  53.0  82.0
2반  73.0  78.0

In [95]:
#결측치를 어떤 값으로 채워넣어보기

df.fillna('hello')

국     영      수
1반  95.0  65.0   74.0
2반  86.0  92.0   50.0
1반  53.0  82.0  hello
2반  73.0  78.0   54.0

In [97]:
df.fillna(0)

국     영     수
1반  95.0  65.0  74.0
2반  86.0  92.0  50.0
1반  53.0  82.0   0.0
2반  73.0  78.0  54.0

In [102]:
df.fillna(round(df.mean(),2))

국     영      수
1반  95.0  65.0  74.00
2반  86.0  92.0  50.00
1반  53.0  82.0  59.33
2반  73.0  78.0  54.00

##**MultiIndex**

In [103]:
#column과 row를 바꿔줌
df.T

1반    2반    1반    2반
국  95.0  86.0  53.0  73.0
영  65.0  92.0  82.0  78.0
수  74.0  50.0   NaN  54.0

In [104]:
df

국     영     수
1반  95.0  65.0  74.0
2반  86.0  92.0  50.0
1반  53.0  82.0   NaN
2반  73.0  78.0  54.0

In [108]:
#학년을 묶어주는 인덱싱
df.index=[['1학년','1학년','2학년','2학년'],['1반','2반','1반','2반']]
df

국     영     수
1학년 1반  95.0  65.0  74.0
    2반  86.0  92.0  50.0
2학년 1반  53.0  82.0   NaN
    2반  73.0  78.0  54.0

In [112]:
df.columns = [['언어','언어','수리'],['국','영','수']]
df

언어          수리
           국     영     수
1학년 1반  95.0  65.0  74.0
    2반  86.0  92.0  50.0
2학년 1반  53.0  82.0   NaN
    2반  73.0  78.0  54.0

In [115]:
#호출방법
print(df['언어']['국'])

1학년  1반    95.0
     2반    86.0
2학년  1반    53.0
     2반    73.0
Name: 국, dtype: float64


In [116]:
df.iloc[0]

언어  국    95.0
    영    65.0
수리  수    74.0
Name: (1학년, 1반), dtype: float64

In [120]:
df.loc["1학년"].loc['1반']

언어  국    95.0
    영    65.0
수리  수    74.0
Name: 1반, dtype: float64

##**데이터 사전 분석**

In [121]:
df

언어          수리
           국     영     수
1학년 1반  95.0  65.0  74.0
    2반  86.0  92.0  50.0
2학년 1반  53.0  82.0   NaN
    2반  73.0  78.0  54.0

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 4 entries, ('1학년', '1반') to ('2학년', '2반')
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   (언어, 국)  4 non-null      float64
 1   (언어, 영)  4 non-null      float64
 2   (수리, 수)  3 non-null      float64
dtypes: float64(3)
memory usage: 384.0+ bytes


In [124]:
df.head()

언어          수리
           국     영     수
1학년 1반  95.0  65.0  74.0
    2반  86.0  92.0  50.0
2학년 1반  53.0  82.0   NaN
    2반  73.0  78.0  54.0

In [125]:
df.tail()

언어          수리
           국     영     수
1학년 1반  95.0  65.0  74.0
    2반  86.0  92.0  50.0
2학년 1반  53.0  82.0   NaN
    2반  73.0  78.0  54.0

In [127]:
df.dtypes

언어  국    float64
    영    float64
수리  수    float64
dtype: object

In [128]:
df.describe()

언어                    수리
               국          영          수
count   4.000000   4.000000   3.000000
mean   76.750000  79.250000  59.333333
std    18.227726  11.176612  12.858201
min    53.000000  65.000000  50.000000
25%    68.000000  74.750000  52.000000
50%    79.500000  80.000000  54.000000
75%    88.250000  84.500000  64.000000
max    95.000000  92.000000  74.000000

In [129]:
df.isnull() #결측치 존재 유무를 알려줌 True 인 자리에 결측치가 있다는 걸 나타낸다.

언어            수리
            국      영      수
1학년 1반  False  False  False
    2반  False  False  False
2학년 1반  False  False   True
    2반  False  False  False

In [130]:
df.isnull().sum()

언어  국    0
    영    0
수리  수    1
dtype: int64

##**값의 연결**

In [131]:
a = pd.DataFrame(np.arange(1,10).reshape(3,3))
a

0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [133]:
b = pd.Series(np.arange(10,40,10))
b

0    10
1    20
2    30
dtype: int64

In [134]:
#및 추가는 append 옆 추가는 concat
pd.concat([a,b],axis=1)

0  1  2   0
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [135]:
pd.concat([a,b],axis=1,ignore_index=True) #열 숫자의 자연스러운 증가는 ignore_index 사용

0  1  2   3
0  1  2  3  10
1  4  5  6  20
2  7  8  9  30

In [136]:
a.append(b,ignore_index=True)

<ipython-input-136-9f6f53509836>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a.append(b,ignore_index=True)


0   1   2
0   1   2   3
1   4   5   6
2   7   8   9
3  10  20  30

#**3.Matplotlib**

In [ ]:
import matplotlib.pyplot as plt